# Mado configuration for Bulgarian Voice Coach
# Fast Rust-based markdown linter
# See: https://github.com/akiomik/mado

[lint]
respect-ignore = true
respect-gitignore = true
output-format = "concise"
quiet = false
exclude = []
# Only enable supported rules, excluding problematic ones
rules = [
  "MD001",  # heading-increment
  "MD002",  # first-heading-h1
  "MD003",  # heading-style
  "MD004",  # ul-style
  "MD005",  # list-indent
  "MD006",  # ul-start-left
  "MD009",  # no-trailing-spaces
  "MD010",  # no-hard-tabs
  "MD012",  # no-multiple-blanks
  "MD013",  # line-length
  "MD014",  # no-shell-dollars
  "MD018",  # no-missing-space-atx
  "MD019",  # no-multiple-space-atx
  "MD020",  # no-missing-space-closed-atx
  "MD021",  # no-multiple-space-closed-atx
  "MD022",  # blanks-around-headings
  "MD023",  # heading-start-left
  "MD024",  # no-duplicate-heading
  "MD025",  # single-title
  "MD026",  # no-trailing-punctuation
  "MD027",  # no-multiple-space-blockquote
  "MD028",  # no-blanks-blockquote
  "MD030",  # list-marker-space
  "MD031",  # blanks-around-fences
  "MD032",  # blanks-around-lists
  "MD033",  # no-inline-html
  "MD034",  # no-bare-urls
  "MD035",  # hr-style
  "MD036",  # no-emphasis-as-heading
  "MD037",  # no-space-in-emphasis
  "MD038",  # no-space-in-code
  "MD039",  # no-space-in-links
  "MD040",  # fenced-code-language
  "MD041",  # first-line-heading
  "MD046",  # code-block-style
  "MD047",  # single-trailing-newline
]
# Skip problematic rules:
# MD007 - ul-indent (too strict about indentation)
# MD029 - ol-prefix (too strict about ordered list numbering) 
# MD031 - blanks-around-fences (will be disabled in markdownlint)
# MD042+ - Not supported by mado

[lint.md009]
# no-trailing-spaces - Allow 2 spaces for line breaks
br-spaces = 2

[lint.md013]
# line-length - Use 120 characters for technical documentation
line-length = 120
code-blocks = false
tables = false

[lint.md025]
# single-title/single-h1 - Allow multiple H1 headers
front-matter-title = ""

[lint.md033]
# no-inline-html - Allow specific HTML elements
allowed-elements = ["details", "summary", "img", "br", "kbd"]

[lint.md041]
# first-line-heading - Allow documents without top-level H1
enabled = false

[lint.md046]
# code-block-style - Prefer fenced code blocks
style = "fenced"

[lint.md053]
# link-reference-style - Disable strict link reference checking
enabled = false