name: API Lint

on:
  push:
    branches: [main]
    paths:
      - "server/**/*.py"
      - "docs/api/**"
      - ".github/workflows/api-lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "server/**/*.py"
      - "docs/api/**"
      - ".github/workflows/api-lint.yml"

jobs:
  api-lint:
    name: Validate OpenAPI Specification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "**/requirements*.txt"

      - name: Set up Python
        run: uv python install 3.12

      - name: Sync dependencies
        run: uv sync

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Generate OpenAPI spec and check if up-to-date
        run: |
          echo "🔍 Generating OpenAPI specification..."

          # Generate the OpenAPI spec using just
          just api-docs

          # Check if git is clean for the OpenAPI file
          if [ -z "$(git status --porcelain docs/api/openapi.json)" ]; then
            echo "✅ OpenAPI specification is up-to-date"
          else
            echo "❌ OpenAPI specification is out of date!"
            echo ""
            echo "The committed docs/api/openapi.json does not match the generated specification."
            echo "Please run 'just api-docs' locally and commit the updated file."
            echo ""
            echo "Differences detected:"
            git diff docs/api/openapi.json || true

            # Exit with error to fail the CI
            exit 1
          fi

      - name: Run Spectral API Linting
        uses: stoplightio/spectral-action@v0.8.13
        with:
          file_glob: "docs/api/openapi.json"
          spectral_ruleset: "docs/api/.spectral.yaml"

      - name: Upload OpenAPI specification
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: openapi-specification
          path: docs/api/openapi.json
