name: API Lint

on:
  push:
    branches: [main]
    paths:
      - 'server/**/*.py'
      - 'docs/api/**'
      - 'client/src/sdk/**'
      - '.github/workflows/api-lint.yml'
  pull_request:
    branches: [main]
    paths:
      - 'server/**/*.py'
      - 'docs/api/**'
      - 'client/src/sdk/**'
      - '.github/workflows/api-lint.yml'

jobs:
  api-lint:
    name: Validate OpenAPI Specification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true

      - name: Generate OpenAPI spec and SDK, check if up-to-date
        run: |
          echo "🔍 Generating OpenAPI specification and TypeScript SDK..."

          # Generate the OpenAPI spec and TypeScript SDK using just
          just api-sdk

          # Check if git is clean for both OpenAPI spec and SDK files
          OPENAPI_CHANGES=$(git status --porcelain docs/api/openapi.json)
          SDK_CHANGES=$(git status --porcelain client/src/sdk/)

          if [ -z "$OPENAPI_CHANGES" ] && [ -z "$SDK_CHANGES" ]; then
            echo "✅ OpenAPI specification and TypeScript SDK are up-to-date"
          else
            echo "❌ OpenAPI specification or TypeScript SDK is out of date!"
            echo ""

            if [ -n "$OPENAPI_CHANGES" ]; then
              echo "OpenAPI specification changes detected:"
              echo "Please run 'just api-sdk' locally and commit the updated files."
              echo ""
              echo "OpenAPI differences:"
              git diff docs/api/openapi.json || true
              echo ""
            fi

            if [ -n "$SDK_CHANGES" ]; then
              echo "TypeScript SDK changes detected:"
              echo "Please run 'just api-sdk' locally and commit the updated files."
              echo ""
              echo "SDK files changed:"
              git status --porcelain client/src/sdk/
              echo ""
            fi

            # Exit with error to fail the CI
            exit 1
          fi

      - name: Run Spectral API Linting
        uses: stoplightio/spectral-action@v0.8.13
        with:
          file_glob: 'docs/api/openapi.json'
          spectral_ruleset: 'docs/api/.spectral.yaml'

      - name: Upload OpenAPI specification
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: openapi-specification
          path: docs/api/openapi.json
