name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-with-just:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: just install

      - name: Run format check
        run: just format-check

      - name: Run linting
        run: just lint

      - name: Run type checking
        run: just py-typecheck

  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitHub Super-Linter
        uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Only validate specific file types with ruff
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_BASH: true