name: Lint

# Explicit minimal permissions for security
permissions:
  contents: read

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  just-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ./bin
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync
          cd client && bun install

      - name: Run comprehensive linting
        run: just lint
