name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install server deps (lint-only)
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff

      - name: Install client deps (lint-only)
        run: |
          cd client
          npm ci || npm i

      - name: Run local linters (Python + JS/CSS)
        run: |
          black --check server
          isort --check-only server
          ruff check server
          cd client && npx prettier -c .

      - name: GitHub Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_TYPESCRIPT_PRETTIER: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true