name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync

      - name: Install system dependencies
        run: |
          # Install eSpeak NG for TTS tests
          sudo apt-get update
          sudo apt-get install -y espeak-ng

      - name: Run unit tests
        run: |
          cd server
          uv run pytest -v --tb=short

      - name: Run integration tests (if any)
        run: |
          cd server
          # Run integration tests with longer timeout for model loading
          uv run pytest test_app.py test_content.py -v --tb=short
        continue-on-error: false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.python-version }}
          path: server/.pytest_cache/
          retention-days: 1

  coverage-report:
    runs-on: ubuntu-latest
    needs: backend-tests
    if: always()
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y espeak-ng

      - name: Run tests with coverage
        run: |
          cd server
          uv run pytest --cov=. --cov-report=xml --cov-report=term

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: server/coverage.xml
          retention-days: 7